web/urls.py
from django.conf.urls import url
from . import views

app_name = 'web'
urlpatterns = [

    url(r'^add_message/',views.add_message,name='add_message'),
    url(r'^test/',views.test,name='test'),
    url(r'^teht/',views.testhtml,name='testhtml'),
        url(r'',views.home,name='home'),
    
]

webapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('web.urls',namespace='web')),
]

web/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

web/views.py
from django.shortcuts import render
from rest_framework import response,status
from rest_framework.decorators import api_view
import os
# Create your views here.
import json

def home(request):
	return render(request, 'home.html')

@api_view(['GET'])
def test(request):
	print('this is current path:',os.getcwd())
	jsondata = open('data.json')

	data = json.load(jsondata)
	jsondata.close()

	return response.Response(data,status = status.HTTP_200_OK)

def testhtml(request):
	return render(request,'testhtml.html')

def add_message(request):
	pass

templates/welcome.html
come on, baby

web/templates/base.html
<html>
<head>
    {% block head %}
        <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    {% endblock %}


	<style>
	#header {
	    background-color:black;
	    color:white;
	    text-align:center;
	    padding:5px;
	}
	#nav {
	    line-height:30px;
	    background-color:#eeeeee;
	    height:300px;
	    width:100px;
	    float:left;
	    padding:5px; 
	}
	#section {
	    width:350px;
	    float:left;
	    padding:10px; 
	}
	#footer {
	    background-color:black;
	    color:white;
	    clear:both;
	    text-align:center;
	    padding:5px; 
	}
	</style>



</head>

<body background="/static/img/timg.jpg" style="background-size: cover">




	<div id="header">
	<h1>head info</h1>
	</div>

	<div id="nav">
	sec_one<br>
	sec_two<br>
	sec_thr<br>
	</div>

	<div id="section">
	{% block body %}
	    {% block section %} {% endblock %}
	{% block script %}{% endblock %}
	{% endblock %}
	</div>

	<div id="footer">
	Copyright from mikelee.
	</div>


</body>

</html>

web/templates/home - 副本.html
{% include 'base.html' %}

{% block script %}

    <script type="text/javascript">
        $(document).ready(function() {
        //wangyi:http://music.163.com/api/playlist/detail?id=58451795
        //douban:https://api.douban.com/v2/book/1220562
        $(function() {
            $.getJSON(
                "http://query.yahooapis.com/v1/public/yql", {q:
                "select * from json where url=\"http://music.163.com/api/playlist/detail?id=58451795\"",
                format:"json"},
            function (data) {
                var json = data.query.results.json.result
                $('#hide').html(json.tracks["24"].name);
                //$('#result').append('<img src="'+ data.query.results.json.result.coverImgUrl +'">');
                //$('#result').append('<embed  src="'+ data.query.results.json.result.tracks["23"].mp3Url +'"  width="200" height="45" />');
                $('#result').append('<audio controls="controls"><source src="'+ json.tracks["24"].mp3Url +'" type="audio/mpeg" />Your browser does not support the audio element.</audio>');
                /*
                var html = '<table border=1 style:{color:white}>';

                var col = json.trackCount/5;
                console.log(col);
                for (var i=0;i<col;i++){
                    html +='<tr>';
                    for(var j=0;j<5&&i*5+j<json.trackCount;j++){

                        var k=i*5+j;
                        console.log(k);
                        var obj = json.tracks[k.toString()];
html +='<td>';
                        html += '<tr><img src="'+obj.album.picUrl+'" width="200" height="200"/></tr>';

html += '<tr style="color: white">'+obj.name+'</tr>';
                        html +='</td>';

                    }
                    html +='</tr>';
                }
                html +='</table>';
                $('#treeList').append(html);*/
            })
        })
        });


    </script>

{% endblock %}
{% block content %}

    <p id="hide" style="color: white">waiting...</p>
    <div id="result"></div>


{% endblock %}

web/templates/home.html
{% extends 'base.html' %}
<!-- extends not include can replace the content in father block-->
{% block script %}

    <script type="text/javascript">
        $(document).ready(function() {
        //wangyi:http://music.163.com/api/playlist/detail?id=58451795
        //douban:https://api.douban.com/v2/book/1220562
            $(function() {
                $.getJSON(
                    "http://query.yahooapis.com/v1/public/yql", {q:
                    "select * from json where url=\"http://music.163.com/api/playlist/detail?id=58451795\"",
                    format:"json"},
                function (data) {
                    var json = data.query.results.json.result
                    $('#hide').html(json.tracks["24"].name);
                    //$('#result').append('<img src="'+ data.query.results.json.result.coverImgUrl +'">');
                    //$('#result').append('<embed  src="'+ data.query.results.json.result.tracks["23"].mp3Url +'"  width="200" height="45" />');
            /////////////////////////////$('#result').append('<audio controls="controls"><source src="'+ json.tracks["24"].mp3Url +'" type="audio/mpeg" />Your browser does not support the audio element.</audio>');
                    /*
                    var html = '<table border=1 style:{color:white}>';

                    var col = json.trackCount/5;
                    console.log(col);
                    for (var i=0;i<col;i++){
                        html +='<tr>';
                        for(var j=0;j<5&&i*5+j<json.trackCount;j++){

                            var k=i*5+j;
                            console.log(k);
                            var obj = json.tracks[k.toString()];
    html +='<td>';
                            html += '<tr><img src="'+obj.album.picUrl+'" width="200" height="200"/></tr>';

    html += '<tr style="color: white">'+obj.name+'</tr>';
                            html +='</td>';

                        }
                        html +='</tr>';
                    }
                    html +='</table>';
                    $('#treeList').append(html);*/
                })
            });
        });
/*
        function search(){

            var exam = 'http://music.163.com/weapi/search/suggest/multimatch?csrf_token=aea830916c42dd2fe5af4659817ebb52';
            var bak = 'http://music.163.com/#/search/m/?%23%2Fdiscover%2Fplaylist%2F=&s="+searchuri+"&type=1';
            var searchId = $('#searchId').val();
            searchuri = encodeURI(searchId);
            console.log(searchuri);
                    $.getJSON(
                        "http://query.yahooapis.com/v1/public/yql", {q:
                        "select * from json where url=\"http://music.163.com/weapi/search/suggest/multimatch?csrf_token=aea830916c42dd2fe5af4659817ebb52\"",
                        format:"json"},
                    function (data) {
                        console.log(data)

                    })


        };*/
    </script>

{% endblock %}
{% block section %}

    <p id="hide" style="color: white">waiting...</p>
    <div id="result"></div>
<!--
<input type="text" id="searchId">
<button  onclick="search()" >submit</button>-->
{% endblock %}

web/templates/testhtml.html
<!DOCTYPE html>

<html>
    <head>

        <title>test</title>
    </head>
    <body>
        <div class="box">
            <ul>
            </ul>
        </div>
        <p><input class="btn" type="button" value="loading..." /></p>
        <span style="cursor:pointer;margin-right:10px;" class="prev">prev</span>
        <span style="cursor:pointer;margin-right:10px;" class="first">first_page</span>
        <span style="cursor:pointer;margin-right:10px;" class="last">last_page</span>
        <span style="cursor:pointer;margin-right:10px;" class="next">next</span>
        <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
        <script type="text/javascript">
            ;(function($){
                var num = 5;//每页显示的个数
                var n = 0;
                var m = -num;
                var testurl = '{% url 'web:test'%}';
                function ajax(pageType){
                    var oul = $(".box").find("ul");
                    var ohtml = "";
                    console.log(testurl);
                    $.ajax({
                        type:"get",
                        url:testurl,
                        dataType:"json",
                        success:function(data){
                            $(oul).empty();
                            if(n < data.length && pageType=="next"){ //上一页
                                n += num;
                                m += num;
                            }else if(m > 0 && pageType=="prev"){ //下一页
                                n -= num;
                                m -= num;
                            }else if(pageType=="first"){ //第一页
                                n = num;
                                m = 0;
                            }else if(pageType=="last"){ //最后一页
                                n = data.length+(data.length%num)-1;
                                m = data.length+(data.length%num)-6;
                            }
                        


                            for (var i = data.length - 1; i >= 0; i--) {
                                if(i>=m && i<n){
                                    ohtml += "<li>" + data['name'] + "</li>";

                                }
                            };

                            $(".box").find("ul").html(ohtml);
                        },
                        error:function error(argument) {
                            alert('error');
                        }
                    });
                };
                $(".next").click(function(){
                    ajax("next");
                });
                $(".prev").click(function(){
                    ajax("prev");
                });
                $(".first").click(function(){
                    ajax("first");
                });
                $(".last").click(function(){
                    ajax("last");
                });
                $(function(){ //初始化
                    ajax("next");
                });
            }(jQuery));
        </script>



    </body>
</html>